### ISSUE TITLE
rai-toolkit calc  returns a timeout 

### ISSUE THREAD

**Issue by geohacker** [developmentseed/rai-toolkit#11]
Running `rai-toolkit calc zm.geojsonld --iso zm --output zm-rai.txt` results in:

```
ok - processing zm
ok - formatted database
ok - imported 4817 master lines
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: "https://github.com/datasets/geo-countries/raw/master/data/countries.geojson", source: TimedOut }', src/pg/country.rs:36:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/calc.rs:91:9
```

**Comment by ingalls** [comment]
@geohacker This is a total guess, but could it be that github doesn't have a CDN server near you? I've tried to replicate this both locally and with a canadian & us VPN and wasn't able to. Is this a file we could host on developmentseed.org?
